namespace SoundFingerprinting.Strides
{
    using System;

#if WINDOWS_UWP
    using System.Runtime.Serialization;
#endif


    /// <summary>
    ///   Random stride object. [min - max Samples stride]
    /// </summary>
#if WINDOWS_UWP
    [DataContract]
#else
    [Serializable]
#endif
    public class RandomStride : IStride
    {
        protected static readonly Random Random = new Random(unchecked((int)DateTime.Now.Ticks));

        private readonly int maxStride;

        private readonly int minStride;

        private int firstStride;

        /// <summary>
        /// Initializes a new instance of the <see cref="RandomStride"/> class. 
        /// </summary>
        /// <param name="minStride">
        /// Minimum stride size, generated by this object
        /// </param>
        /// <param name="maxStride">
        /// Maximum stride size, generated by this object
        /// </param>
        public RandomStride(int minStride, int maxStride)
        {
            if (minStride > maxStride)
            {
                throw new ArgumentException("Bad arguments. Max stride should be bigger than Min stride");
            }

            this.minStride = minStride;
            this.maxStride = maxStride;
            firstStride = Random.Next(minStride, maxStride);
        }

        public RandomStride(int minStride, int maxStride, int firstStride)
            : this(minStride, maxStride)
        {
            this.firstStride = firstStride;
        }

#if WINDOWS_UWP
        [DataMember]
#endif
        public int Min
        {
            get
            {
                return minStride;
            }
        }

#if WINDOWS_UWP
        [DataMember]
#endif
        public int Max
        {
            get
            {
                return maxStride;
            }
        }

#if WINDOWS_UWP
        [DataMember]
#endif
        public int FirstStride
        {
            get
            {
                return firstStride;
            }

            protected set
            {
                firstStride = value;
            }
        }

        public virtual int GetNextStride()
        {
            return Random.Next(minStride, maxStride);
        }
    }
}